import type { FinanceData } from './types';
import { defaultSettings } from './dashboardMock';

export const createInitialFinanceData = (): FinanceData => ({
  version: 1,
  settings: defaultSettings,
  accounts: [
    { id: 'account-pro', name: 'Compte pro', kind: 'professional', openingBalance: 2500 },
    { id: 'account-personal', name: 'Compte perso', kind: 'personal', openingBalance: 800 },
    { id: 'account-urssaf-tax', name: 'Provision Urssaf + impôt', kind: 'provision', openingBalance: 600 },
    { id: 'account-savings', name: 'Épargne sécurité', kind: 'savings', openingBalance: 1200 },
  ],
  invoices: [
    {
      id: 'invoice-001',
      clientName: 'Client Alpha',
      status: 'paid',
      totalTTC: 1200,
      issueDate: '2026-05-01',
      dueDate: '2026-05-15',
      paymentDate: '2026-05-03',
      paymentAccountId: 'account-pro',
    },
    {
      id: 'invoice-002',
      clientName: 'Client Beta',
      status: 'paid',
      totalTTC: 650,
      issueDate: '2026-05-10',
      dueDate: '2026-05-25',
      paymentDate: '2026-05-18',
      paymentAccountId: 'account-pro',
    },
    {
      id: 'invoice-003',
      clientName: 'Client Gamma',
      status: 'sent',
      totalTTC: 900,
      issueDate: '2026-05-20',
      dueDate: '2026-06-05',
      paymentDate: null,
      paymentAccountId: null,
    },
  ],
  transactions: [
    {
      id: 'transaction-income-001',
      kind: 'income',
      label: 'Paiement Client Alpha',
      amount: 1200,
      date: '2026-05-03',
      fromAccountId: null,
      toAccountId: 'account-pro',
      invoiceId: 'invoice-001',
    },
    {
      id: 'transaction-income-002',
      kind: 'income',
      label: 'Paiement Client Beta',
      amount: 650,
      date: '2026-05-18',
      fromAccountId: null,
      toAccountId: 'account-pro',
      invoiceId: 'invoice-002',
    },
    {
      id: 'transaction-expense-001',
      kind: 'expense',
      label: 'Abonnement outils',
      amount: 250,
      date: '2026-05-12',
      fromAccountId: 'account-pro',
      toAccountId: null,
    },
    {
      id: 'transaction-transfer-001',
      kind: 'transfer',
      label: 'Virement perso',
      amount: 300,
      date: '2026-05-19',
      fromAccountId: 'account-pro',
      toAccountId: 'account-personal',
    },
  ],
});
