import type { FinanceData } from './types';
import { FINANCE_DATA_VERSION } from './types';
import { defaultSettings } from './dashboardMock';

/**
 * Jeu de démonstration volontairement fictif : aucune donnée réelle ne doit
 * figurer dans le dépôt, qui est public. Les vraies valeurs entrent par la
 * saisie ou par l'import d'une sauvegarde.
 */
export const createInitialFinanceData = (): FinanceData => ({
  version: FINANCE_DATA_VERSION,
  settings: defaultSettings,
  // La génération des prélèvements s'amorcera sur le mois d'ouverture, pas sur
  // celui des données de démonstration.
  recurringChargeAutoPostFrom: null,
  accounts: [
    { id: 'account-pro', name: 'Compte pro', kind: 'professional', openingBalance: 2500 },
    { id: 'account-personal', name: 'Compte perso', kind: 'personal', openingBalance: 800 },
    { id: 'account-urssaf-tax', name: 'Provision Urssaf + impôt', kind: 'provision', openingBalance: 600 },
    { id: 'account-savings', name: 'Épargne sécurité', kind: 'savings', openingBalance: 1200 },
  ],
  invoices: [
    {
      id: 'invoice-001',
      clientName: 'Client Alpha',
      status: 'paid',
      totalTTC: 1200,
      issueDate: '2026-05-01',
      dueDate: '2026-05-15',
      paymentDate: '2026-05-03',
      paymentAccountId: 'account-pro',
      prospectId: 'prospect-001',
    },
    {
      id: 'invoice-002',
      clientName: 'Client Beta',
      status: 'paid',
      totalTTC: 650,
      issueDate: '2026-05-10',
      dueDate: '2026-05-25',
      paymentDate: '2026-05-18',
      paymentAccountId: 'account-pro',
    },
    {
      id: 'invoice-003',
      clientName: 'Client Gamma',
      status: 'sent',
      totalTTC: 900,
      issueDate: '2026-05-20',
      dueDate: '2026-06-05',
      paymentDate: null,
      paymentAccountId: null,
      prospectId: 'prospect-002',
    },
  ],
  transactions: [
    {
      id: 'transaction-income-001',
      kind: 'income',
      label: 'Paiement Client Alpha',
      amount: 1200,
      date: '2026-05-03',
      fromAccountId: null,
      toAccountId: 'account-pro',
      invoiceId: 'invoice-001',
    },
    {
      id: 'transaction-income-002',
      kind: 'income',
      label: 'Paiement Client Beta',
      amount: 650,
      date: '2026-05-18',
      fromAccountId: null,
      toAccountId: 'account-pro',
      invoiceId: 'invoice-002',
    },
    {
      id: 'transaction-expense-001',
      kind: 'expense',
      label: 'Abonnement outils',
      amount: 250,
      date: '2026-05-12',
      fromAccountId: 'account-pro',
      toAccountId: null,
    },
    {
      id: 'transaction-transfer-001',
      kind: 'transfer',
      label: 'Virement perso',
      amount: 300,
      date: '2026-05-19',
      fromAccountId: 'account-pro',
      toAccountId: 'account-personal',
    },
  ],
  recurringCharges: [
    { id: 'charge-001', label: 'Loyer', amount: 700, scope: 'personal', dayOfMonth: 5, active: true },
    { id: 'charge-002', label: 'Abonnements outils', amount: 60, scope: 'professional', dayOfMonth: 1, active: true },
  ],
  areMonths: [
    { month: '2026-05', fullMonthlyARE: 1416, actualARE: 1012 },
    { month: '2026-06', fullMonthlyARE: 1416, actualARE: null },
  ],
  prospects: [
    {
      id: 'prospect-001',
      name: 'Client Alpha',
      company: 'Alpha Conseil',
      source: 'Réseau professionnel',
      temperature: 'hot',
      status: 'signed',
      nextFollowUpDate: null,
      notes: 'Mission cadrée en avril, facturée en mai.',
      createdAt: '2026-04-08',
      estPrescripteur: false,
    },
    {
      id: 'prospect-002',
      name: 'Client Gamma',
      company: 'Gamma Studio',
      source: 'Petit-déjeuner entrepreneurs',
      temperature: 'hot',
      status: 'active',
      nextFollowUpDate: null,
      notes: 'Devis envoyé, attend la validation de son associé.',
      createdAt: '2026-05-12',
      estPrescripteur: false,
    },
    {
      id: 'prospect-003',
      name: 'Client Delta',
      company: null,
      source: 'Recommandation',
      temperature: 'cold',
      status: 'active',
      nextFollowUpDate: null,
      notes: 'Contact transmis, jamais appelé.',
      createdAt: '2026-06-02',
      estPrescripteur: false,
    },
  ],
  interactions: [
    {
      id: 'interaction-001',
      prospectId: 'prospect-001',
      date: '2026-04-08',
      channel: 'meeting',
      note: 'Premier rendez-vous, besoin confirmé.',
    },
    {
      id: 'interaction-002',
      prospectId: 'prospect-002',
      date: '2026-05-20',
      channel: 'email',
      note: 'Devis envoyé.',
    },
  ],
  opportunities: [
    {
      id: 'opportunity-001',
      prospectId: 'prospect-002',
      title: 'Automatisation reporting client',
      pipeline: 'projet',
      stageId: 'proposal',
      amount: 3200,
      recurring: false,
      monthlyAmount: null,
      probability: 55,
      probabilityOverride: false,
      expectedCloseDate: '2026-06-30',
      originEvent: 'Petit-déjeuner entrepreneurs',
      referrerProspectId: null,
      funding: null,
      status: 'open',
      lossReason: null,
      statusDate: null,
      createdAt: '2026-05-12',
    },
  ],
  stageChanges: [
    {
      id: 'stage-change-001',
      opportunityId: 'opportunity-001',
      fromStageId: null,
      toStageId: 'identified',
      date: '2026-05-12',
      daysInPreviousStage: null,
    },
    {
      id: 'stage-change-002',
      opportunityId: 'opportunity-001',
      fromStageId: 'identified',
      toStageId: 'proposal',
      date: '2026-05-20',
      daysInPreviousStage: 8,
    },
  ],
  tasks: [
    {
      id: 'task-001',
      prospectId: 'prospect-002',
      opportunityId: 'opportunity-001',
      label: 'Relancer sur la validation de l’associé',
      dueDate: '2026-06-05',
      priority: 'high',
      status: 'open',
      completedAt: null,
      createdAt: '2026-05-20',
    },
    {
      id: 'task-002',
      prospectId: 'prospect-003',
      opportunityId: null,
      label: 'Premier appel de découverte',
      dueDate: '2026-06-10',
      priority: 'normal',
      status: 'open',
      completedAt: null,
      createdAt: '2026-06-02',
    },
  ],
});
